/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomRoomIdDisplayRouteImport } from './routes/room.$roomId.display'
import { Route as RoomRoomIdControlRouteImport } from './routes/room.$roomId.control'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoomIdDisplayRoute = RoomRoomIdDisplayRouteImport.update({
  id: '/room/$roomId/display',
  path: '/room/$roomId/display',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoomIdControlRoute = RoomRoomIdControlRouteImport.update({
  id: '/room/$roomId/control',
  path: '/room/$roomId/control',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/room/$roomId/control': typeof RoomRoomIdControlRoute
  '/room/$roomId/display': typeof RoomRoomIdDisplayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/room/$roomId/control': typeof RoomRoomIdControlRoute
  '/room/$roomId/display': typeof RoomRoomIdDisplayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/room/$roomId/control': typeof RoomRoomIdControlRoute
  '/room/$roomId/display': typeof RoomRoomIdDisplayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/room/$roomId/control' | '/room/$roomId/display'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/room/$roomId/control' | '/room/$roomId/display'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/room/$roomId/control'
    | '/room/$roomId/display'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  RoomRoomIdControlRoute: typeof RoomRoomIdControlRoute
  RoomRoomIdDisplayRoute: typeof RoomRoomIdDisplayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$roomId/display': {
      id: '/room/$roomId/display'
      path: '/room/$roomId/display'
      fullPath: '/room/$roomId/display'
      preLoaderRoute: typeof RoomRoomIdDisplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$roomId/control': {
      id: '/room/$roomId/control'
      path: '/room/$roomId/control'
      fullPath: '/room/$roomId/control'
      preLoaderRoute: typeof RoomRoomIdControlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  RoomRoomIdControlRoute: RoomRoomIdControlRoute,
  RoomRoomIdDisplayRoute: RoomRoomIdDisplayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
